### ISSUE TITLE
Google font blocks page load

### ISSUE THREAD

**Issue by jedwood** [presidential-innovation-fellows/rfpez#11]
If it doesn't load for some reason, page rendering is blocked until timeout.

**Comment by jedwood** [comment]
One solution is to use some of the options here: https://developers.google.com/webfonts/docs/webfont_loader . But given that the "real" design might not even use a Google font, I'm just going to mark this is wontfix for now. If we find it becoming a problem before the real design is up, then we can revisit.

**Comment by ajb** [comment]
I don't know if that's the right choice. If page rendering is really blocked, we can't go live with that. There's gotta be a solution that falls back to a non webfont. I'll investigate.

**Comment by jedwood** [comment]
Solutions definitely there, they just all have tradeoffs. Agreed that if it
continues to pop up as a problem, it's worth fixing.

**Comment by ajb** [comment]
I mean, considering the fact that most government buildings have sites and ports blocked, and the site won't load if the font doesn't load, I'd say it's a pretty big problem.
