### ISSUE TITLE
Blank slate design for when there are no projects

### ISSUE THREAD

**Issue by jedwood** [presidential-innovation-fellows/rfpez#114]

**Comment by ajb** [comment]
can you explain?

**Comment by jedwood** [comment]
I'm pulling the phrase from this classic:
http://gettingreal.37signals.com/ch09_The_Blank_Slate.php

But in this particular case I'm thinking of something very simple that
should take about 5 minutes; just a "There are no open projects right now,
but you can subscribe to the RSS feeds/email alerts..." on our projects
page, instead of this:

http://rfpez.sba.gov/projects
