### ISSUE TITLE
How do we deal with hourly vs. fixed bid contracts?

### ISSUE THREAD

**Issue by ajb** [presidential-innovation-fellows/rfpez#126]

**Comment by ajb** [comment]
Maybe this includes a "period of performance" section?

**Comment by ajb** [comment]
Hey @cjoh @jedwood we should probably prioritize this. Do you guys have any ideas on how we'd accomplish this? One possibility that I have in mind is on the `projects/new` page, letting an officer select between "hourly" and "flat rate", and displaying the bid form appropriately. Would that cover our bases?

**Comment by jedwood** [comment]
I think it sounds like a good starting point at least, and we can get more
feedback.

**Comment by ajb** [comment]
K, I'll start on this now. I'm tempted to add a "price breakdown" textarea as well, since that's something that Katelyn said they would want to see.

**Comment by jedwood** [comment]
fight the feature creep! But of course, add it if you think it's worth
putting in there.
