### ISSUE TITLE
Can't leave a comment as admin

### ISSUE THREAD

**Issue by jedwood** [presidential-innovation-fellows/rfpez#136]
Same error as #135

**Comment by ajb** [comment]
is this a duplicate of GH-118?

**Comment by jedwood** [comment]
Don't think so. This is an ie issue that makes it so you can't leave a comment even on the project you own.

**Comment by ajb** [comment]
Got it, the "admin" part confused me, no worries.  

---

Adam Becker | Project RFP-EZ (http://presidential-innovation-fellows.github.com/rfpez-blog) | 510.928.9111 | Adam.Becker@sba.gov

**Comment by jedwood** [comment]
Now seems only broken in ie7, but not seeing any errors. Hitting the submit button just doesn't do anything.

**Comment by jedwood** [comment]
Making an executive call that ie7 is not priority for this pilot.
