### ISSUE TITLE
Sections in SOW can't be re-ordered

### ISSUE THREAD

**Issue by jedwood** [presidential-innovation-fellows/rfpez#138]
drag/drop doesn't seem to work

**Comment by ajb** [comment]
if this isn't an easy fix, i'm tempted to just let it sit until we redesign SOW composer...

**Comment by jedwood** [comment]
agreed. I'm adding a "bug" tag only to things that seem like they're show stoppers, which this isn't.

**Comment by jedwood** [comment]
Looks like this got solved somewhere along the way- even for ie7!
