### ISSUE TITLE
Make SOW Composer a bit more restrictive?

### ISSUE THREAD

**Issue by ajb** [presidential-innovation-fellows/rfpez#38]
The fact that users can edit the full SOW body negates some of the benefits we get from restricting the format of the SOW. If we remove the "edit full document" step and instead add a few more customization features, it might benefit us.

**Comment by jedwood** [comment]
Much agreed, especially for this pilot.

**Comment by jedwood** [comment]
my bad- referenced the wrong issue

**Comment by ajb** [comment]
@jedwood @cjoh opinions needed on this:

when we rework SOW composer, which I think should be soonish, how about just storing the templates as JSON? it seems to me right now that the template parser is very fragile, and writing templates for a non-technical person isn't really that much easier than if it were json. thoughts?

**Comment by jedwood** [comment]
After stewing on it a bit, my tendency is to think we should either go the
direction you recommend (more geeky, making the backend cleaner and less
fragile) or further in the direction of non-geek (e.g. text input fields
and/or basic WYSIWYG controls somehow). I think you're right about how it
stands right now possibly being a non-optimal middle-ground.

**Comment by ajb** [comment]
Yeah, definitely. I like how if we go geeky, there's always the option of making a GUI for it later.

**Comment by ajb** [comment]
Hooray, we finally did this! Closing.
