### ISSUE TITLE
Don't allow officers to view a bid that has been deleted

### ISSUE THREAD

**Issue by ajb** [presidential-innovation-fellows/rfpez#46]

**Comment by jedwood** [comment]
I can't reproduce, and a very quick scan of various places in the code looks like checks are being done for things like `->where_deleted_by_vendor(0)` . Is there a specific scenario or edge case where this is still happening?

**Comment by ajb** [comment]
I can reproduce, I'll show you. Should be simple, just adding a filter. I'll do it now.
