### ISSUE TITLE
Hotkeys remap to match vim and Gmail

### ISSUE THREAD

**Issue by jedwood** [presidential-innovation-fellows/rfpez#61]
Anybody opposed? I'm lovin' the hotkeys, but I'm fighting years of muscle memory trying to use them. :) Guessing it's the same for you @cjoh ?

**Comment by ajb** [comment]
feel free to submit a PR for this one, should be dead simple to do. idgaf what the hotkeys are.

**Comment by jedwood** [comment]
on it, thx.
