### ISSUE TITLE
Friendlier start to SoW walkthrough

### ISSUE THREAD

**Issue by jedwood** [presidential-innovation-fellows/rfpez#66]
Start with simple re-ordering of the flow so that the high-effort "background and scope" writing section isn't the first task.

**Comment by ajb** [comment]
@jedwood i'm thinking we can just add a "skip this for now" button/link to the step so that it's clear it can be skipped... opinions?

**Comment by jedwood** [comment]
Gut reaction is to either just leave it like it is, or try switching the
order.

**Comment by ajb** [comment]
Ok, let's just leave it until we can get some more solid feedback and/or observe more usage.
