### ISSUE TITLE
fix styles on small browser windows

### ISSUE THREAD

**Issue by ajb** [presidential-innovation-fellows/rfpez#77]
we could go full responsive-design, but i don't think anyone will be used SOW composer from a phone.

what about going responsive for everything the vendor will see?  thoughts @cjoh @jedwood?

**Comment by jedwood** [comment]
Likelihood that people will really interact with it via a mobile device?
Probably low. But it might be one of those things that's worth doing for
a.) the exercise of doing it and b.) scoring a few points of cred with our
target market of savvy web dev companies.

**Comment by ajb** [comment]
Completed in 831a01053f for all pages that a vendor sees. Woo!
