### ISSUE TITLE
Ask in signup form "where did you hear about RFPEZ"?

### ISSUE THREAD

**Issue by ajb** [presidential-innovation-fellows/rfpez#97]
@cjoh @jedwood

**Comment by jedwood** [comment]
Sounds great to me. We can just put it as an optional field right before
they click "create" when they're creating a new account.

**Comment by ajb** [comment]
@cjoh can you take a moment to create the &lt;option&gt;s for this?

**Comment by jedwood** [comment]
Going to put it as an open text field for now, since I think that will get us the richest data without requiring an exhaustive list of predefined options. But it's easy to add <option>s if @cjoh has a good list!
